# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-16 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=11)),
                ('serpassword', models.CharField(max_length=12)),
                ('nickname', models.CharField(max_length=20)),
            ],
        ),
    ]
