# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-16 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoomModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='serpassword',
            new_name='userpassword',
        ),
    ]
